"""data_now3

Revision ID: 1686975befb1
Revises: 33b8544a962c
Create Date: 2022-10-25 17:20:56.628962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1686975befb1'
down_revision = '33b8544a962c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
