"""data_now3

Revision ID: 33b8544a962c
Revises: b80dc9e2a802
Create Date: 2022-10-25 17:20:31.514246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b8544a962c'
down_revision = 'b80dc9e2a802'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
