"""user_test4

Revision ID: 408732149d5b
Revises: 39c8f66449f9
Create Date: 2022-10-23 16:42:43.459826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '408732149d5b'
down_revision = '39c8f66449f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
