"""user_test2

Revision ID: 487907a584bf
Revises: e36984019a4b
Create Date: 2022-10-23 16:16:29.809820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487907a584bf'
down_revision = 'e36984019a4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
