"""user_test2

Revision ID: e36984019a4b
Revises: e10f459391d0
Create Date: 2022-10-23 16:15:44.966651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e36984019a4b'
down_revision = 'e10f459391d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.drop_column('user', 'date')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
